### ISSUE TITLE
Async: Does the PollyExecuteAsync method require async await

### ISSUE THREAD

**Issue by mcquiggd** [Pro-Coded/Polly.Contrib.Decorator#2]
We are dealing with an async method that is passed to Polly's ExecuteAsync method.

This is done via passing a delegate created by an expression lambda.

The PollyExecute methods created by the Decorator accept Action and Func.

Do we require the wrapped method to have the async-await syntax, as well as the PollyExecute method, which executes the delegate via ExecuteAsync?

**Comment by reisenberger** [comment]
Issue #1 asked how we could identify which methods in an interface _could_ be called with `await`.  Assuming #1 provides a suitable basis for identifying them, this issue asks _should_ `Polly.Contrib.Decorator` generate code so that it internally calls all `Task`-returning methods with `await`?

One potential issue here is that while other languages separate these, .NET uses one type (`Task`) for two different kinds of work: I/O-bound work and cpu-bound work.  (Others use different terms: [Stephen Cleary uses promise task and delegate task](https://blog.stephencleary.com/2014/04/a-tour-of-task-part-0-overview.html).)  Delegate tasks are typically used with the Task Parallel Library for parallelising CPU-bound work; promise tasks are typically used with `async`/`await` for I/O bound work.

It seems reasonable to assume that the predominant uses of Polly with `Task`-returning methods will be around I/O type work: transient faults in I/O are its core application; I haven't heard of Polly used with TPL CPU-bound work (tho it could be).  So a reasonable default could be to use `async`/`await` on all `Task`-returning methods (but document that assumption).

## `async`/`await` elision

[`async`/`await` elision](https://blog.stephencleary.com/2016/12/eliding-async-await.html) however probably lets us dispose of the whole problem. 

+ If `Polly.Contrib.Decorator` uses `async`/`await` elision, there is no need to distinguish I/O-bound and CPU-bound uses of `Task`
+ The [sample output shared from `Polly.Contrib.Decorator`](https://pollytalk.slack.com/files/mcquiggd/F66CPM62C/PollyDecoratorSample_cs.cs) seems to fit the simple-pass-through definition outlined in [Stephen Cleary's blog, where async/await elision would not be a problem](https://blog.stephencleary.com/2016/12/eliding-async-await.html).
+ Polly in any case [always uses the full `async`/`await` unelided](https://github.com/App-vNext/Polly/blob/75456beee1c4e25b88ab34057434bdc1eec30480/src/Polly.Shared/PolicyAsync.cs#L543-L558), when calling into the Policy implementation, and when each policy implementation calls the user delegate, meaning exceptions thrown by the user delegate will be correctly placed into the return `Task` passed back up the decorating/wrapping calls.

---

What do you think?

**Comment by mcquiggd** [comment]
As discussed on the Polly Slack channel, I have implemented two options, to cover both scenarios:

`Implement Interface with Polly`

`Implement Interface with Polly, including async await`

It's been an excellent discussion, and a learning experience.
